server:
  port: 8007
spring:
  application:
    name: micro-administrador
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/administrador?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

  data:
    mongodb:
      uri: mongodb://localhost:27017/parada
